### PR TITLE
Add customizable indentation and unindent

### PR DESCRIPTION
**Pull request by jeroenvisser101**
You can now press shift+tab to unindent and set custom indent width (tabs, 2 spaces, 8 spaces, it will work no matter what)

### CODE REVIEW

**Comment by desertkun** [comment]
Was waiting exactly for this!

**Comment by jeroenvisser101** [comment]
btw, the shift-tab only works when you're at the beginning of the line (or rather, when your cursor can go back 4 characters), but I think it would be more 'natural', to allow it anywhere on the line and activate when the first part matches the indentation. I'll change it.

**Comment by kazzkiq** [comment]
@jeroenvisser101 Sorry for the delay. The closer to New Year, the busier we get, right? 🏃 

Thanks for the awesome contribution!

**Comment by jeroenvisser101** [comment]
@kazzkiq no worries! Appreciate you taking the time to look at it 👍

**Comment by lehni** [comment]
@kazzkiq I think this functionality is now broken in 1.0+

**Comment by kazzkiq** [comment]
@lehni You're right. This code will have to be imported to the new major version.

**Pull request merged**
