### PR TITLE
- Added all requested RTL features.

### PR DESCRIPTION
**Pull request by AndreYonadam**
- Can now specify the initial text direction.
- Dynamically handles changes in text direction when the textarea's direction is changed by the browser. Changes are reflected by the placeholder element as well.

### CODE REVIEW

**Comment by kazzkiq** [comment]
It seems there are some bugs when trying to write code on RTL-enabled editor. Here is a sample:

bug

No idea if this is a browser bug or just some missing CSS/JS property for dealing with RTL texts.

**Comment by AndreYonadam** [comment]
I think that might because english isn't an RTL language. Try switching to a RTL language such as Arabic or Hebrew.

**Comment by AndreYonadam** [comment]
Just as a heads up. This isn't an issue with the editor. I tested the actual comment section here and it has the same effect when in the right-to-left mode.
jan-17-2017 21-51-23

**Comment by kazzkiq** [comment]
It seems @MajidCS tested it with a RTL language and everything worked as expected (see #26), so I'm merging the PR.

As always, thanks for the incredible work @AndreYonadam! 🎉

**Pull request merged**
