### PR TITLE
removeChild isn't faster than innerHTML

### PR DESCRIPTION
**Pull request by NeXTs**
http://codepen.io/NeXTs/pen/LVodbO?editors=101
Only place where removeChild loop may be preferable is handling table
elements for ie9 and lower, as old ie's does not support to do innerHTML
for table elements.

### CODE REVIEW

**Comment by kazzkiq** [comment]
Hmm, weird. The assumption was based on [this perf test](http://jsperf.com/innerhtml-vs-removechild/2), which showed a big gap between ops. But your code seems otherwise.

Although this performance concern is just too small to even consider a serious issue on CodeFlask.js, I will still give it a deeper look to try to find out what is causing the performance gap.

**Comment by NeXTs** [comment]
Yeah, weird. When I saw jsperf results, my assumptions were like gap occurs because of inline elements, but I repeated that experiment with my codepen and this was not confirmed. At codepen innerHTML still faster despite element type.

**Comment by NeXTs** [comment]
btw another jsperf test between those two.
http://jsperf.com/innerhtml-vs-removechild/67
At this time without large gap

**Comment by kazzkiq** [comment]
Ok, so I made some tests on my machine and all of them showed `innerHTML` as the winner. So to have no more doubts I've made a test rendering `<textarea>` elements just as the plugin does itself, then removing them with both `innerHTML` and `removeChild`.

With this approach `innerHTML` still mercilessly beats `removeChild` running around 2x faster.

So, yeah, `innerHTML` ftw.

Final test: http://jsfiddle.net/a42eczre/

**Pull request merged**
